### ISSUE TITLE
Question about delete options

### ISSUE THREAD

**Issue by Diegus83** [book-tools/audnexus-kometa-series#1]
Hi! Thanks for putting this guide together. It worked great.
I have a question about this config option

`unconfigured: true`

I could not find it in the documentation: 
https://metamanager.wiki/en/latest/config/operations.html#delete-collections

Should it be `configured: true`?

**Comment by djdembeck** [comment]
It may have changed from when the guide was written, but now you are correct.

**Comment by csandman** [comment]
I believe it did change since I wrote the guide, but I'm also not really sure what the specific goal was with that config haha. I think the equivalent would be `configured: false`, but I'm not entirely sure. I'll have to look into this again, and probably do some testing to see what the proper setup is.

Also sorry, totally missed this issue when you first made it.

**Comment by csandman** [comment]
Sorry for never checking this, but I finally just tested it. You're right, the `unconfigured` option hasn't existed for a while. I updated the config in the docs to include both new config options, and the result looks like this:

```yml
      delete_collections:
        managed: true
        configured: false
        less: 1
```

Adding the `managed: true` flag ensures it only deletes collections that were made by Kometa.

Then the `configured: false` flag basically just says, match any collections that aren't part of the current collection configuration. I believe this is specifically the case, because once no more books match the mood tag checker, it's no longer considered "part of the configuration". I'm not positive if this is how it works, but this worked for me haha.
